# Generated by Django 2.2.7 on 2019-12-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
    ]
