# Generated by Django 2.2.7 on 2019-12-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb2_app', '0002_auto_20191213_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.CharField(max_length=50),
        ),
    ]
