# Generated by Django 2.2.7 on 2019-12-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb2_app', '0003_auto_20191213_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(),
        ),
    ]
